pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test

  publish:
    image: plugins/docker
    registry: docker.goeasy.io # 仓库
    repo: docker.goeasy.io/droneci # docker仓库地址
    secrets: [ docker_username, docker_password ]
    tags:
      - 1.1