pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm test
      - pwd
      - ls

  publish:
    image: plugins/docker
    registry: docker.goeasy.io # 仓库
    repo: docker.goeasy.io/droneci # docker仓库地址
    secrets: [ docker_username, docker_password ]
    tags:
      - 1.4
  deploy:
    image: appleboy/drone-ssh
    host: 8.218.55.232
    username: root
    port: 22
    password: Uwant123!
    script:
      - docker login -u uwantsoft -p uwantsoft123 docker.goeasy.io
      - docker pull docker.goeasy.io/droneci:1.4
      - docker run -d -p 8080:8080 --name droneci1.4 docker.goeasy.io/droneci:1.4